-- ============================================================================
-- 04_rbac_setup.sql
-- Role-based access control for the AI evaluation framework
-- Two-tier model: Analyst (dev), Reviewer (approve), Deployer (prod)
-- ============================================================================

USE ROLE SECURITYADMIN;

-- ============================================================
-- Custom Roles
-- ============================================================

CREATE ROLE IF NOT EXISTS RETAIL_AI_ANALYST;
COMMENT ON ROLE RETAIL_AI_ANALYST IS 'Data analysts who create/edit semantic views in DEV';

CREATE ROLE IF NOT EXISTS RETAIL_AI_REVIEWER;
COMMENT ON ROLE RETAIL_AI_REVIEWER IS 'Reviewers who approve promotions from DEV to PROD';

CREATE ROLE IF NOT EXISTS RETAIL_AI_DEPLOYER;
COMMENT ON ROLE RETAIL_AI_DEPLOYER IS 'CI/CD service account that deploys to DEV and PROD';

CREATE ROLE IF NOT EXISTS RETAIL_AI_ADMIN;
COMMENT ON ROLE RETAIL_AI_ADMIN IS 'Admin role for full framework management';

-- ============================================================
-- Role hierarchy
-- ============================================================
GRANT ROLE RETAIL_AI_ANALYST  TO ROLE RETAIL_AI_REVIEWER;
GRANT ROLE RETAIL_AI_REVIEWER TO ROLE RETAIL_AI_ADMIN;
GRANT ROLE RETAIL_AI_DEPLOYER TO ROLE RETAIL_AI_ADMIN;
GRANT ROLE RETAIL_AI_ADMIN    TO ROLE SYSADMIN;

-- ============================================================
-- Warehouse grants
-- ============================================================
GRANT USAGE ON WAREHOUSE RETAIL_AI_EVAL_WH TO ROLE RETAIL_AI_ANALYST;
GRANT USAGE ON WAREHOUSE RETAIL_AI_EVAL_WH TO ROLE RETAIL_AI_REVIEWER;
GRANT USAGE ON WAREHOUSE RETAIL_AI_EVAL_WH TO ROLE RETAIL_AI_DEPLOYER;

-- ============================================================
-- ANALYST: Full access to DEV, read-only on PROD
-- ============================================================
GRANT USAGE ON DATABASE RETAIL_AI_DEV TO ROLE RETAIL_AI_ANALYST;
GRANT USAGE ON ALL SCHEMAS IN DATABASE RETAIL_AI_DEV TO ROLE RETAIL_AI_ANALYST;
GRANT SELECT ON ALL TABLES IN SCHEMA RETAIL_AI_DEV.ANALYTICS TO ROLE RETAIL_AI_ANALYST;
GRANT CREATE SEMANTIC VIEW ON SCHEMA RETAIL_AI_DEV.SEMANTIC TO ROLE RETAIL_AI_ANALYST;
GRANT ALL ON ALL SEMANTIC VIEWS IN SCHEMA RETAIL_AI_DEV.SEMANTIC TO ROLE RETAIL_AI_ANALYST;

GRANT USAGE ON DATABASE RETAIL_AI_PROD TO ROLE RETAIL_AI_ANALYST;
GRANT USAGE ON ALL SCHEMAS IN DATABASE RETAIL_AI_PROD TO ROLE RETAIL_AI_ANALYST;
GRANT SELECT ON ALL TABLES IN SCHEMA RETAIL_AI_PROD.ANALYTICS TO ROLE RETAIL_AI_ANALYST;

GRANT USAGE ON DATABASE RETAIL_AI_EVAL TO ROLE RETAIL_AI_ANALYST;
GRANT USAGE ON ALL SCHEMAS IN DATABASE RETAIL_AI_EVAL TO ROLE RETAIL_AI_ANALYST;
GRANT SELECT ON ALL TABLES IN SCHEMA RETAIL_AI_EVAL.RESULTS TO ROLE RETAIL_AI_ANALYST;

-- ============================================================
-- DEPLOYER: Deploy semantic views and agents to DEV and PROD
-- ============================================================
GRANT USAGE ON DATABASE RETAIL_AI_DEV TO ROLE RETAIL_AI_DEPLOYER;
GRANT USAGE ON ALL SCHEMAS IN DATABASE RETAIL_AI_DEV TO ROLE RETAIL_AI_DEPLOYER;
GRANT SELECT ON ALL TABLES IN SCHEMA RETAIL_AI_DEV.ANALYTICS TO ROLE RETAIL_AI_DEPLOYER;
GRANT CREATE SEMANTIC VIEW ON SCHEMA RETAIL_AI_DEV.SEMANTIC TO ROLE RETAIL_AI_DEPLOYER;
GRANT ALL ON ALL SEMANTIC VIEWS IN SCHEMA RETAIL_AI_DEV.SEMANTIC TO ROLE RETAIL_AI_DEPLOYER;

GRANT USAGE ON DATABASE RETAIL_AI_PROD TO ROLE RETAIL_AI_DEPLOYER;
GRANT USAGE ON ALL SCHEMAS IN DATABASE RETAIL_AI_PROD TO ROLE RETAIL_AI_DEPLOYER;
GRANT SELECT ON ALL TABLES IN SCHEMA RETAIL_AI_PROD.ANALYTICS TO ROLE RETAIL_AI_DEPLOYER;
GRANT CREATE SEMANTIC VIEW ON SCHEMA RETAIL_AI_PROD.SEMANTIC TO ROLE RETAIL_AI_DEPLOYER;
GRANT ALL ON ALL SEMANTIC VIEWS IN SCHEMA RETAIL_AI_PROD.SEMANTIC TO ROLE RETAIL_AI_DEPLOYER;

GRANT USAGE ON DATABASE RETAIL_AI_EVAL TO ROLE RETAIL_AI_DEPLOYER;
GRANT USAGE ON ALL SCHEMAS IN DATABASE RETAIL_AI_EVAL TO ROLE RETAIL_AI_DEPLOYER;
GRANT INSERT, SELECT ON ALL TABLES IN SCHEMA RETAIL_AI_EVAL.RESULTS TO ROLE RETAIL_AI_DEPLOYER;

-- ============================================================
-- REVIEWER: Can view everything, approve promotions
-- ============================================================
GRANT USAGE ON DATABASE RETAIL_AI_EVAL TO ROLE RETAIL_AI_REVIEWER;
GRANT USAGE ON ALL SCHEMAS IN DATABASE RETAIL_AI_EVAL TO ROLE RETAIL_AI_REVIEWER;
GRANT SELECT ON ALL TABLES IN SCHEMA RETAIL_AI_EVAL.RESULTS TO ROLE RETAIL_AI_REVIEWER;

-- ============================================================
-- Future grants for new objects
-- ============================================================
GRANT SELECT ON FUTURE TABLES IN SCHEMA RETAIL_AI_DEV.ANALYTICS TO ROLE RETAIL_AI_ANALYST;
GRANT SELECT ON FUTURE TABLES IN SCHEMA RETAIL_AI_PROD.ANALYTICS TO ROLE RETAIL_AI_ANALYST;
GRANT SELECT ON FUTURE TABLES IN SCHEMA RETAIL_AI_EVAL.RESULTS TO ROLE RETAIL_AI_ANALYST;
